# Generated by Django 4.2.27 on 2026-02-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='Imagen',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='Imagen',
        ),
        migrations.AddField(
            model_name='director',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='directores/'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/'),
        ),
    ]
